version: "0.1"
user: vishalakshi.hiremani
key: GNNhFtVUKgCzeJRHTkcqHZkspBaQBALbrO4X7m0ILMCPPpTpMs
testSuites: []
pre: ['mvn -Dmaven.repo.local=./.m2 dependency:resolve']
preDirectives:
    commands: ['mvn -Dmaven.repo.local=./.m2 dependency:resolve']
    maxRetries: 0
    shell: ""
    workingDirectory: ""
postDirectives:
    commands: []
    shell: ""
    workingDirectory: ""
jobLabel:
    - selenium-cucumber-java
    - win
    - autosplit
runson: win
autosplit: true
concurrency: 2
testDiscovery:
    args:
        featureFilePaths: src/test/java/features/
        frameWork: java
    command: C:\Algoshack\Java\HyperExecute\AlgoAFScript_202306210734\.hyperexecute\snooper.exe  --targetOs=win --featureFilePaths=src/test/java/features/ --frameWork=java
    mode: static
    type: automatic
testDiscoveryResult:
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:31
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:57
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:82
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:117
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:157
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:188
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:226
    - src/test/java/features/SAAS_Functional_TCs_Web Automation_SRS_TestCases_202306210730591.feature:2658
testRunnerCommand: mvn test `-Dplatname=win `-Dmaven.repo.local=./.m2 `-Dcucumber.features="$test"
globalTimeout: 150
testSuiteTimeout: 150
testSuiteStep: 150
cacheDirectories:
    - .m2
cacheKey: '{{ checksum "pom.xml" }}'
maxRetries: 1
jobID: db44b438-8e31-4327-9da0-9648b7cdf19b
uploadArtefacts:
    - name: FinalReport
      path:
        - ExtentReports/**
      email:
        to: []
uploadArtifacts:
    - name: FinalReport
      path:
        - ExtentReports/**
      email:
        to: []
codeDirectory: AlgoAFScript_202306210734
report: true
partialReports:
    type: json
    location: target/
    frameworkName: extent-native
    email:
        to: []
framework:
    name: ""
    flags: []
    discoveryFlags: []
    discoveryType: ""
    runnerFlags: []
    workingDirectory: ""
    isTestNGXMLSuite: false
    defaultReports: true
    additional_args: null
    licenseKey: ""
    userdefinediscovery: false
    toscaArgs: null
    version: ""
    downloadURL: ""
cypress: false
betaFeature:
    setPartiallyCompletedAsCompleted: false
combineTasksInMatrixMode: false
captureScreenRecordingForScenarios: false
maxRetriesPreSteps: 0
triggerMode: false
collectLocalGitData: true
dynamicAllocation: false
appium: false
